config/routes.rb
Rails.application.routes.draw do
  # Authentication
  get '/auth/auth0/callback', to: 'auth0#callback'
  post '/auth/logout', to: 'auth0#logout'
  get '/auth/failure', to: 'auth0#failure'

  # TODO: Enable this is production, implement authentication and authorization
  # to this endpoint before enabling it in production!
  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'landing#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    return @current_user if defined?(@current_user)

    @current_user = begin
      user_id = session[:user_id]

      if user_id
        User.find_by(id: user_id)
      end
    end
  end

  def append_info_to_payload(payload)
    super

    payload[:user_id] = current_user.id if current_user.present?
  end
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def callback
    auth = request.env.fetch('omniauth.auth')
    info = auth.fetch('info')

    result = UserAuthenticator.new(
      auth0_uid: auth.fetch('uid'),
      auth0_info: info,
    ).call

    session[:user_id] = result.user.id

    if result.new_user?
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def logout
    session[:user_id] = nil

    redirect_to(
      "https://#{ENV.fetch('AUTH0_DOMAIN')}/v2/logout?" +
      "client_id=#{ENV.fetch('AUTH0_CLIENT_ID')}&" +
      "returnTo=#{URI.encode(root_url)}"
    )
  end

  def failure
    render text: 'Not implemented', status: 200
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing/index.html.erb
<h1>Hello</h1>


<% if current_user.present? %>
	<h2><%= current_user.name %></h2>
	<%= button_to 'Sign out', auth_logout_path, method: :post %>
<% else %>
	<button data-auth0-lock>Sign in</button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWebStarter</title>
    <%= csrf_meta_tags %>

    <script type="text/javascript">
      var AppConfig = {
        auth0_client_id: '<%= ENV.fetch('AUTH0_CLIENT_ID', nil) %>',
        auth0_domain: '<%= ENV.fetch('AUTH0_DOMAIN', nil) %>',
        auth0_redirect_url: '<%= auth_auth0_callback_url %>',
      };
    </script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script src="https://cdn.auth0.com/js/lock/11.3/lock.min.js"></script>
  </body>
</html>